apiVersion: apps/v1
kind: Deployment
metadata:
  name: landon-dep
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: landon-dep
  template: 
    metadata: 
      labels:
        app: landon-dep
    spec: 
      containers:
        - name: landon-dep
          image: landondelaney/cit270
          command: ["npm"]
          args: ["run", "start"]
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".125"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 443
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet: 
              path: /
              port: 443
            initialDelaySeconds: 3
            periodSeconds: 3


